name: MS - feature build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get PR information
        id: pr-info
        uses: actions/github-script@v4
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const pr = await github.pulls.get({
              owner,
              repo,
              pull_number: number,
            });

            console.log('::set-output name=head-sha::' + pr.data.head.sha);
            console.log('::set-output name=base-sha::' + pr.data.base.sha);

      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.pr-info.outputs.head-sha }}
          fetch-depth: "0"

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1

      - name: Install .NET tools
        run: |
          dotnet tool install --global dotnet-affected --version 2.0.0-preview-1

      - name: Get affected builds
        run: |
          dotnet affected --from ${{ steps.pr-info.outputs.head-sha }} --to ${{ steps.pr-info.outputs.base-sha }}

      - name: Build MS
        run: |
          dotnet build affected.proj --configuration Release

      - name: Run unit tests
        run: |
          dotnet test affected.proj --no-restore
