name: Test - if branch works (without merge)

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Share status
        uses: actions/github-script@v4
        with:
          script: |
            const {owner, repo} = context.issue
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Build ${{ needs.prepare-pr-build.outputs.microservice-name }} completed',
            });
